### ISSUE TITLE
Cross Compiling does not seem possible

### ISSUE THREAD

**Issue by jonnius** [sailfishos-chum/picotts#1]
How can one do cross-compiling? If I do `make` in Clickable, it complains that I'd need to pass `--host` argument to `./configure`. Problem is it seems the only way to compile is via `make`. Do I need to tweak the Makefile?

**Comment by rinigus** [comment]
Probably you should fork it and then make a special version allowing cross-compilation. And then use your fork for ubports click

**Comment by jonnius** [comment]
Done: https://github.com/jonnius/pkg-picotts
